name: mosaic_app
description: Пазлы из ваших фотографий с нейросетью

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  image_picker: ^1.0.7
  image: ^4.1.7
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  vibration: ^1.9.0
  audioplayers: ^5.2.1
  lottie: ^3.1.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/l10n/app_ru.arb
    - assets/l10n/app_en.arb

  generate: true
